### ISSUE TITLE
Bonjour Fails to install - High CPU load

### ISSUE THREAD

**Issue by K47S** [OPCFoundation/UA-LDS#10] opened 2017-04-25 10:00 UTC
Hello,

we have tried to install the LDS Version 1.03.348 from the OPC Foundation Homepage on one of our machines. The setup completes without error but the OPCF Bonjour Service is missing from the service list (is not installed).

The LDS runs but it consumes between 33% and 100% of one of our cores.

I have tried reinstalling many times but it just won't work. Version 1.02 works perfectly!

This is the log:
> Tue Apr 25 10:49:16 [9960]: Error: OpenService '
> Tue Apr 25 10:49:16 [8348]: Error: OpenService '
> Tue Apr 25 10:49:16 [8348]: Could not start Bonjour Service
> Tue Apr 25 10:49:25 [8348]: Failed to open windows certificate store! (0x80000000)
> Tue Apr 25 10:49:25 [8348]: Could not verify certificate in windows certificate store (0x80000000).
> Tue Apr 25 10:49:25 [8348]: Failed to open windows certificate store! (0x80000000)
> Tue Apr 25 10:49:25 [8348]: Could not verify certificate in windows certificate store (0x80000000).
> Tue Apr 25 10:49:25 [8348]: Failed to open windows certificate store! (0x80000000)
> Tue Apr 25 10:49:25 [8348]: Could not verify certificate in windows certificate store (0x80000000).
> Tue Apr 25 10:49:25 [8348]: Failed to open windows certificate store! (0x80000000)
> Tue Apr 25 10:49:25 [8348]: Could not verify certificate in windows certificate store (0x80000000).
> Tue Apr 25 10:49:25 [8348]: Failed to open windows certificate store! (0x80000000)
> Tue Apr 25 10:49:25 [8348]: Could not verify certificate in windows certificate store (0x80000000).
> Tue Apr 25 10:49:25 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:49:32 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:49:39 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:49:46 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:49:53 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:50:00 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:50:10 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:50:17 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:50:24 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:50:31 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:50:39 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:50:46 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:50:53 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:00 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:08 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:51:16 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:23 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:30 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:38 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:51:45 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:51:52 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:00 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:08 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:52:15 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:22 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:29 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:37 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:52:44 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:51 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:52:58 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:06 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:53:13 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:20 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:28 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:36 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:53:43 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:50 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:53:57 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:05 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:54:12 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:19 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:27 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:35 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:54:42 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:49 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:54:56 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:55:03 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:55:10 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:55:17 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:55:24 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:55:31 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:55:38 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:55:45 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:55:53 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:56:00 [8348]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
> Tue Apr 25 10:56:08 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:56:15 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
> Tue Apr 25 10:56:22 [8348]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563

**Comment by gabirusu** [comment] 2017-04-25 11:01
Hello,

could you please provide more info related to the machine where you encountered these problems? Information like operating system, clean installation or upgrade of LDS and/or Bonjour or anything that you consider meaningful would help us a lot.

**Comment by K47S** [comment] 2017-04-26 05:47
Hello,

the machines are running on Windows 7 32.
I have created setup logs for Uninstalling the LDS and reinstalling the LDS. 

Had to upload them on pastebin because they are too long for Github comments.
Uninstall: [https://pastebin.com/AHHr20RN](https://pastebin.com/AHHr20RN)
Install: [https://pastebin.com/kCdZCBcE](https://pastebin.com/kCdZCBcE)

**Comment by sorintopan** [comment] 2017-05-09 08:56
The first part of the bug (Bonjour Fails to install) is still not fixed. The other problem with the processor load is fixed in v 1.03.362

At this point we could not reproduce the problem ("Bonjour Fails to install..") on any of the test machines. The error itself is when Bonjour (mDNSResponder) is trying to register itself as a service.
The error message isn't helpful: „There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: Action_RegBonjourService.4E6EDC62C0B245CF831D3C5D4806F990, location: C:\Program Files\Common Files\OPC Foundation\UA\Discovery\bin\mDNSResponder.exe, command: -install”
There are many posts on Internet from people complaining they receive this message when installing iTunes (Bonjour is installed with it). The problem is probably with the Apple product itself and not with the LDS installer package.

**Closed** 2018-02-06 15:35 UTC
Labels: Not reproducible, fixed
